# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: samples_short.tsv

# Folder containing the blast db
blast_db: "../rRNA-16S/16SMicrobial_db/16SMicrobial"

# Folder containing the trainee files for seqmatch
rdp_trainee: "../rRNA-16S/RDP11/trainee"

#name of the project
project_name: "PRJNA33175_333"
